"""Phase 2 — initial schema

Revision ID: 55ff637163df
Revises: 
Create Date: 2026-07-17 10:04:32.862829

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55ff637163df'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('epics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_epics')),
    sa.UniqueConstraint('key', name=op.f('uq_epics_key'))
    )
    op.create_table('key_counters',
    sa.Column('entity', sa.String(length=30), nullable=False),
    sa.Column('value', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('entity', name=op.f('pk_key_counters'))
    )
    op.create_table('labels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_labels')),
    sa.UniqueConstraint('name', name=op.f('uq_labels_name'))
    )
    op.create_table('modules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_modules')),
    sa.UniqueConstraint('name', name=op.f('uq_modules_name'))
    )
    op.create_table('sprints',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Text(), nullable=True),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.Enum('Planned', 'Active', 'Completed', name='sprintstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.CheckConstraint('end_date >= start_date', name=op.f('ck_sprints_end_after_start')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sprints')),
    sa.UniqueConstraint('number', name=op.f('uq_sprints_number'))
    )
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sprints_status'), ['status'], unique=False)

    op.create_table('tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('name', name=op.f('uq_tags_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('Admin', 'QA', 'Developer', name='userrole', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('username', name=op.f('uq_users_username'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('features',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_features_module_id_modules'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_features')),
    sa.UniqueConstraint('module_id', 'name', name=op.f('uq_features_module_id'))
    )
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_features_module_id'), ['module_id'], unique=False)

    op.create_table('stories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('Open', 'In Progress', 'Done', name='storystatus', native_enum=False), nullable=False),
    sa.Column('story_points', sa.Integer(), nullable=True),
    sa.Column('epic_id', sa.Integer(), nullable=True),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['epic_id'], ['epics.id'], name=op.f('fk_stories_epic_id_epics'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_stories_sprint_id_sprints'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stories')),
    sa.UniqueConstraint('key', name=op.f('uq_stories_key'))
    )
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stories_epic_id'), ['epic_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_sprint_id'), ['sprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_stories_status'), ['status'], unique=False)

    op.create_table('defects',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_key', sa.String(length=20), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('expected_result', sa.Text(), nullable=True),
    sa.Column('actual_result', sa.Text(), nullable=True),
    sa.Column('steps_to_reproduce', sa.Text(), nullable=True),
    sa.Column('platform', sa.Enum('Android', 'iOS', 'Web', 'API', name='platform', native_enum=False), nullable=False),
    sa.Column('environment', sa.Enum('Development', 'QA', 'Staging', 'UAT', 'Production', name='environment', native_enum=False), nullable=False),
    sa.Column('app_version', sa.String(length=50), nullable=True),
    sa.Column('build_number', sa.String(length=50), nullable=True),
    sa.Column('os_version', sa.String(length=50), nullable=True),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('severity', sa.Enum('Critical', 'High', 'Medium', 'Low', name='severity', native_enum=False), nullable=False),
    sa.Column('priority', sa.Enum('P0', 'P1', 'P2', 'P3', name='priority', native_enum=False), nullable=False),
    sa.Column('criticality', sa.Enum('Low', 'Medium', 'High', 'Critical', name='criticality', native_enum=False), nullable=True),
    sa.Column('status', sa.Enum('Open', 'In Progress', 'Ready for QA', 'Retest', 'Verified', 'Closed', 'Rejected', 'Duplicate', 'Deferred', 'Blocked', 'Cannot Reproduce', name='defectstatus', native_enum=False), nullable=False),
    sa.Column('module_id', sa.Integer(), nullable=False),
    sa.Column('feature_id', sa.Integer(), nullable=True),
    sa.Column('story_id', sa.Integer(), nullable=True),
    sa.Column('sprint_id', sa.Integer(), nullable=True),
    sa.Column('reporter_id', sa.Integer(), nullable=False),
    sa.Column('assigned_qa_id', sa.Integer(), nullable=True),
    sa.Column('assigned_developer_id', sa.Integer(), nullable=True),
    sa.Column('eta', sa.Date(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(), nullable=True),
    sa.Column('resolution_type', sa.Enum('Fixed', "Won't Fix", 'Duplicate', 'Not a Bug', 'Cannot Reproduce', 'Deferred', name='resolutiontype', native_enum=False), nullable=True),
    sa.Column('root_cause', sa.Text(), nullable=True),
    sa.Column('regression_required', sa.Boolean(), nullable=False),
    sa.Column('regression_status', sa.Enum('Pending', 'In Progress', 'Passed', 'Failed', name='regressionstatus', native_enum=False), nullable=True),
    sa.Column('duplicate_of_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_developer_id'], ['users.id'], name=op.f('fk_defects_assigned_developer_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['assigned_qa_id'], ['users.id'], name=op.f('fk_defects_assigned_qa_id_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['duplicate_of_id'], ['defects.id'], name=op.f('fk_defects_duplicate_of_id_defects'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['feature_id'], ['features.id'], name=op.f('fk_defects_feature_id_features'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['module_id'], ['modules.id'], name=op.f('fk_defects_module_id_modules'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['reporter_id'], ['users.id'], name=op.f('fk_defects_reporter_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['sprint_id'], ['sprints.id'], name=op.f('fk_defects_sprint_id_sprints'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['story_id'], ['stories.id'], name=op.f('fk_defects_story_id_stories'), ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_defects')),
    sa.UniqueConstraint('defect_key', name=op.f('uq_defects_defect_key'))
    )
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_defects_assigned_developer_id'), ['assigned_developer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_assigned_qa_id'), ['assigned_qa_id'], unique=False)
        batch_op.create_index('ix_defects_created_at', ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_environment'), ['environment'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_feature_id'), ['feature_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_module_id'), ['module_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_platform'), ['platform'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_reporter_id'), ['reporter_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_sprint_id'), ['sprint_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_defects_story_id'), ['story_id'], unique=False)

    op.create_table('activity_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=True),
    sa.Column('actor_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.Enum('created', 'updated', 'status_changed', 'assigned', 'commented', 'attachment_added', 'attachment_removed', 'deleted', name='activityaction', native_enum=False), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=True),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], name=op.f('fk_activity_log_actor_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], name=op.f('fk_activity_log_defect_id_defects'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_activity_log'))
    )
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_activity_log_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_activity_log_defect_id'), ['defect_id'], unique=False)
        batch_op.create_index('ix_activity_log_entity', ['entity_type', 'entity_id'], unique=False)

    op.create_table('attachments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('uploaded_by_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Enum('Screenshot', 'Video', 'Log', 'Other', name='attachmentkind', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=True),
    sa.Column('size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], name=op.f('fk_attachments_defect_id_defects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_attachments_uploaded_by_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_attachments')),
    sa.UniqueConstraint('stored_filename', name=op.f('uq_attachments_stored_filename'))
    )
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_attachments_defect_id'), ['defect_id'], unique=False)

    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_edited', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_comments_author_id_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], name=op.f('fk_comments_defect_id_defects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['parent_id'], ['comments.id'], name=op.f('fk_comments_parent_id_comments'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comments'))
    )
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_comments_author_id'), ['author_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_defect_id'), ['defect_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_comments_parent_id'), ['parent_id'], unique=False)

    op.create_table('defect_labels',
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('label_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], name=op.f('fk_defect_labels_defect_id_defects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['label_id'], ['labels.id'], name=op.f('fk_defect_labels_label_id_labels'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('defect_id', 'label_id', name=op.f('pk_defect_labels'))
    )
    with op.batch_alter_table('defect_labels', schema=None) as batch_op:
        batch_op.create_index('ix_defect_labels_label_id', ['label_id'], unique=False)

    op.create_table('defect_tags',
    sa.Column('defect_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['defect_id'], ['defects.id'], name=op.f('fk_defect_tags_defect_id_defects'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_defect_tags_tag_id_tags'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('defect_id', 'tag_id', name=op.f('pk_defect_tags'))
    )
    with op.batch_alter_table('defect_tags', schema=None) as batch_op:
        batch_op.create_index('ix_defect_tags_tag_id', ['tag_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('defect_tags', schema=None) as batch_op:
        batch_op.drop_index('ix_defect_tags_tag_id')

    op.drop_table('defect_tags')
    with op.batch_alter_table('defect_labels', schema=None) as batch_op:
        batch_op.drop_index('ix_defect_labels_label_id')

    op.drop_table('defect_labels')
    with op.batch_alter_table('comments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_comments_parent_id'))
        batch_op.drop_index(batch_op.f('ix_comments_defect_id'))
        batch_op.drop_index(batch_op.f('ix_comments_author_id'))

    op.drop_table('comments')
    with op.batch_alter_table('attachments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_attachments_defect_id'))

    op.drop_table('attachments')
    with op.batch_alter_table('activity_log', schema=None) as batch_op:
        batch_op.drop_index('ix_activity_log_entity')
        batch_op.drop_index(batch_op.f('ix_activity_log_defect_id'))
        batch_op.drop_index(batch_op.f('ix_activity_log_created_at'))
        batch_op.drop_index(batch_op.f('ix_activity_log_actor_id'))

    op.drop_table('activity_log')
    with op.batch_alter_table('defects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_defects_story_id'))
        batch_op.drop_index(batch_op.f('ix_defects_status'))
        batch_op.drop_index(batch_op.f('ix_defects_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_defects_severity'))
        batch_op.drop_index(batch_op.f('ix_defects_reporter_id'))
        batch_op.drop_index(batch_op.f('ix_defects_priority'))
        batch_op.drop_index(batch_op.f('ix_defects_platform'))
        batch_op.drop_index(batch_op.f('ix_defects_module_id'))
        batch_op.drop_index(batch_op.f('ix_defects_feature_id'))
        batch_op.drop_index(batch_op.f('ix_defects_environment'))
        batch_op.drop_index('ix_defects_created_at')
        batch_op.drop_index(batch_op.f('ix_defects_assigned_qa_id'))
        batch_op.drop_index(batch_op.f('ix_defects_assigned_developer_id'))

    op.drop_table('defects')
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stories_status'))
        batch_op.drop_index(batch_op.f('ix_stories_sprint_id'))
        batch_op.drop_index(batch_op.f('ix_stories_epic_id'))

    op.drop_table('stories')
    with op.batch_alter_table('features', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_features_module_id'))

    op.drop_table('features')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))

    op.drop_table('users')
    op.drop_table('tags')
    with op.batch_alter_table('sprints', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sprints_status'))

    op.drop_table('sprints')
    op.drop_table('modules')
    op.drop_table('labels')
    op.drop_table('key_counters')
    op.drop_table('epics')
    # ### end Alembic commands ###
